### ISSUE TITLE
[Question] negpipの効き方がおかしい

### ISSUE THREAD

**Issue by za-wa-n-go** [laksjdjf/cd-tuner_negpip-ComfyUI#1]
negpipを繋ぐだけで全く違う結果になってしまうのですが、これは正常動作なのでしょうか。
イラスト系がリアル系になるだけではなく、プロンプトとは全く違う画像が生成されてしまいます。

[こちら](https://github.com/shiimizu/ComfyUI_smZNodes)のClipTextEncode++を使用しているのですが、公式のClipTextEncode以外はNGだったりするでしょうか。
プロンプトエディティングが使えるので、出来れば++の方を使いたいのですが・・・

**Comment by laksjdjf** [comment]
このノードには対応していないです。

**Comment by za-wa-n-go** [comment]
返答ありがとうございます。公式ノードで試してみます！
